# Generated by Django 2.2.1 on 2019-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
