# Generated by Django 2.2.1 on 2019-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactquery',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='contactquery',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
